"""initial

Revision ID: 840165cde40c
Revises:
Create Date: 2026-05-13 13:48:29.984616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "840165cde40c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("shopify_store_id", sa.Integer(), nullable=True),
        sa.Column(
            "shop_domain", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stores_shop_domain"), "stores", ["shop_domain"], unique=True
    )
    op.create_index(
        op.f("ix_stores_shopify_store_id"), "stores", ["shopify_store_id"], unique=True
    )
    op.create_table(
        "collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("shopify_collection_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("handle", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "store_id", "shopify_collection_id", name="uq_store_collection"
        ),
    )
    op.create_index(
        "idx_collections_store_id", "collections", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_collections_shopify_collection_id"),
        "collections",
        ["shopify_collection_id"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("shopify_product_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("handle", sa.Text(), nullable=True),
        sa.Column("vendor", sa.Text(), nullable=True),
        sa.Column("product_type", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "shopify_product_id", name="uq_store_product"),
    )
    op.create_index("idx_products_handle", "products", ["handle"], unique=False)
    op.create_index(
        "idx_products_product_type", "products", ["product_type"], unique=False
    )
    op.create_index("idx_products_status", "products", ["status"], unique=False)
    op.create_index("idx_products_store_id", "products", ["store_id"], unique=False)
    op.create_index("idx_products_vendor", "products", ["vendor"], unique=False)
    op.create_index(
        op.f("ix_products_shopify_product_id"),
        "products",
        ["shopify_product_id"],
        unique=False,
    )
    op.create_index(op.f("ix_products_title"), "products", ["title"], unique=False)
    op.create_table(
        "product_collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id", "product_id", "collection_id"),
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("shopify_image_id", sa.BigInteger(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_images_product_id", "product_images", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_images_shopify_image_id"),
        "product_images",
        ["shopify_image_id"],
        unique=False,
    )
    op.create_table(
        "product_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_product_options_product_id",
        "product_options",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("shopify_variant_id", sa.BigInteger(), nullable=False),
        sa.Column("sku", sa.Text(), nullable=True),
        sa.Column("barcode", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("compare_at_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("inventory_quantity", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("weight_unit", sa.Text(), nullable=True),
        sa.Column("taxable", sa.Boolean(), nullable=True),
        sa.Column("requires_shipping", sa.Boolean(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "shopify_variant_id", name="uq_store_variant"),
    )
    op.create_index(
        "idx_variants_barcode", "product_variants", ["barcode"], unique=False
    )
    op.create_index(
        "idx_variants_product_id", "product_variants", ["product_id"], unique=False
    )
    op.create_index("idx_variants_sku", "product_variants", ["sku"], unique=False)
    op.create_index(
        "idx_variants_store_id", "product_variants", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_variants_shopify_variant_id"),
        "product_variants",
        ["shopify_variant_id"],
        unique=False,
    )
    op.create_table(
        "variant_option_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("option_name", sa.Text(), nullable=False),
        sa.Column("option_value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_variant_option_variant_id",
        "variant_option_values",
        ["variant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_variant_option_variant_id", table_name="variant_option_values")
    op.drop_table("variant_option_values")
    op.drop_index(
        op.f("ix_product_variants_shopify_variant_id"), table_name="product_variants"
    )
    op.drop_index("idx_variants_store_id", table_name="product_variants")
    op.drop_index("idx_variants_sku", table_name="product_variants")
    op.drop_index("idx_variants_product_id", table_name="product_variants")
    op.drop_index("idx_variants_barcode", table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index("idx_product_options_product_id", table_name="product_options")
    op.drop_table("product_options")
    op.drop_index(
        op.f("ix_product_images_shopify_image_id"), table_name="product_images"
    )
    op.drop_index("idx_images_product_id", table_name="product_images")
    op.drop_table("product_images")
    op.drop_table("product_collections")
    op.drop_index(op.f("ix_products_title"), table_name="products")
    op.drop_index(op.f("ix_products_shopify_product_id"), table_name="products")
    op.drop_index("idx_products_vendor", table_name="products")
    op.drop_index("idx_products_store_id", table_name="products")
    op.drop_index("idx_products_status", table_name="products")
    op.drop_index("idx_products_product_type", table_name="products")
    op.drop_index("idx_products_handle", table_name="products")
    op.drop_table("products")
    op.drop_index(
        op.f("ix_collections_shopify_collection_id"), table_name="collections"
    )
    op.drop_index("idx_collections_store_id", table_name="collections")
    op.drop_table("collections")
    op.drop_index(op.f("ix_stores_shopify_store_id"), table_name="stores")
    op.drop_index(op.f("ix_stores_shop_domain"), table_name="stores")
    op.drop_table("stores")
    # ### end Alembic commands ###
