"""fixed primary key issue

Revision ID: 9710081371b9
Revises: 840165cde40c
Create Date: 2026-05-13 21:54:43.762423

"""

from typing import Sequence, Union
import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "9710081371b9"
down_revision: Union[str, Sequence[str], None] = "840165cde40c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_product_collection", "product_collections", ["product_id", "collection_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_product_collection", "product_collections", type_="unique")
    # ### end Alembic commands ###
